### ISSUE TITLE
建议注册页面加入返回登录操作

### ISSUE THREAD

**Issue by 123jixinyu** [lex-land/lex#27]
![image](https://user-images.githubusercontent.com/16695723/60568456-77655000-9d9f-11e9-91e1-ae62bd06ad75.png)
![image](https://user-images.githubusercontent.com/16695723/60568540-b4314700-9d9f-11e9-802a-9b246beaec5d.png)

**Comment by briefguo** [comment]
嗯，这个看着主流的网站是有从注册页回去的。不过这里咋说呢。我这里有几点考虑：
1. 注册页的入口在登录页，进入注册页已经很大程度上说明用户没账号才进去注册的。
2. 其实点击logo能回到login

**Comment by briefguo** [comment]
已经支持了
